wip

diff --git a/script/get-closure-library b/script/get-closure-library
--- a/script/get-closure-library
+++ b/script/get-closure-library
@@ -11,15 +11,18 @@ if [ ! -f $output ]; then
   echo "Fetching Google Closure Library..."
 
   if ! [ -d planck-cljs/lib/closure ]; then
-    mkdir -p planck-cljs/lib
+    mkdir -p planck-cljs/lib/closure
+    mkdir -p planck-cljs/lib/third_party/closure
     cd planck-cljs/lib
-    curl --retry 3 -LO -s https://github.com/google/closure-library/archive/v$GCL_RELEASE.zip || { echo "Download failed."; exit 1; }
-    unzip -qu v$GCL_RELEASE.zip
-    mv closure-library-$GCL_RELEASE/closure .
-    mv closure-library-$GCL_RELEASE/third_party .
+    curl --retry 3 -LO -s https://repo1.maven.org/maven2/org/clojure/google-closure-library/$GCL_RELEASE/google-closure-library-$GCL_RELEASE.jar || { echo "Download failed."; exit 1; }
+    curl --retry 3 -LO -s https://repo1.maven.org/maven2/org/clojure/google-closure-library-third-party/$GCL_RELEASE/google-closure-library-third-party-$GCL_RELEASE.jar || { echo "Download failed."; exit 1; }
+    jar xf google-closure-library-$GCL_RELEASE.jar goog
+    mv goog closure
+    jar xf google-closure-library-third-party-$GCL_RELEASE.jar goog
+    mv goog third_party/closure
     echo "Cleaning up Google Closure Library archive..."
-    rm -rf closure-library-$GCL_RELEASE
-    rm v$GCL_RELEASE.zip
+    rm google-closure-library-$GCL_RELEASE.jar
+    rm google-closure-library-third-party-$GCL_RELEASE.jar
     cd ../..
   fi
 
